"""created sentiment table

Revision ID: 067d0c41e586
Revises: bc19b6c4b575
Create Date: 2026-07-17 21:32:03.120515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '067d0c41e586'
down_revision: Union[str, Sequence[str], None] = 'bc19b6c4b575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sentiment_mean', sa.Float(), nullable=True),
    sa.Column('confidence_mean', sa.Float(), nullable=True),
    sa.Column('headline_count', sa.Integer(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_symbol'), 'sentiment', ['symbol'], unique=False)
    op.add_column('NewsAPI', sa.Column('headline_count', sa.Integer(), nullable=True))
    op.drop_column('NewsAPI', 'title_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('title_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('NewsAPI', 'headline_count')
    op.drop_index(op.f('ix_sentiment_symbol'), table_name='sentiment')
    op.drop_table('sentiment')
    # ### end Alembic commands ###
