"""removed mean columns from newsapi

Revision ID: 41d67fc4f35f
Revises: 067d0c41e586
Create Date: 2026-07-17 22:06:22.025023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '41d67fc4f35f'
down_revision: Union[str, Sequence[str], None] = '067d0c41e586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsAPI', 'sentiment_mean')
    op.drop_column('NewsAPI', 'negative_count')
    op.drop_column('NewsAPI', 'positive_count')
    op.drop_column('NewsAPI', 'headline_count')
    op.drop_column('NewsAPI', 'confidence_mean')
    op.drop_column('NewsAPI', 'neutral_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('neutral_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('NewsAPI', sa.Column('confidence_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('NewsAPI', sa.Column('headline_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('NewsAPI', sa.Column('positive_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('NewsAPI', sa.Column('negative_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('NewsAPI', sa.Column('sentiment_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
