"""added order audit table

Revision ID: 54c0f3c36967
Revises: e0da06093ff0
Create Date: 2026-07-28 21:32:39.734415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '54c0f3c36967'
down_revision: Union[str, Sequence[str], None] = 'e0da06093ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradeaudit',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('risk_check_passed', sa.Boolean(), nullable=False),
    sa.Column('risk_check_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('validation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_side', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_qty', sa.Integer(), nullable=True),
    sa.Column('order_filled_qty', sa.Float(), nullable=True),
    sa.Column('order_filled_avg_price', sa.Float(), nullable=True),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradeaudit_symbol'), 'tradeaudit', ['symbol'], unique=False)
    op.create_index(op.f('ix_tradeaudit_timestamp'), 'tradeaudit', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradeaudit_timestamp'), table_name='tradeaudit')
    op.drop_index(op.f('ix_tradeaudit_symbol'), table_name='tradeaudit')
    op.drop_table('tradeaudit')
    # ### end Alembic commands ###
