"""added confidence to newsapi table

Revision ID: 604d72b1b59d
Revises: bdd4544445bf
Create Date: 2026-06-23 13:58:15.896049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '604d72b1b59d'
down_revision: Union[str, Sequence[str], None] = 'bdd4544445bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsAPI', 'confidence')
    # ### end Alembic commands ###
