"""created newsapi table

Revision ID: 6b0d51391066
Revises: e279ef89b15a
Create Date: 2026-06-19 16:19:41.652607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6b0d51391066"
down_revision: Union[str, Sequence[str], None] = "e279ef89b15a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "NewsAPI",
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_NewsAPI_symbol"), "NewsAPI", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_NewsAPI_timestamp"), "NewsAPI", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_NewsAPI_timestamp"), table_name="NewsAPI")
    op.drop_index(op.f("ix_NewsAPI_symbol"), table_name="NewsAPI")
    op.drop_table("NewsAPI")
    # ### end Alembic commands ###
