"""added signal columns to returns table

Revision ID: 8849c688d775
Revises: 56f35dac21a0
Create Date: 2026-07-15 15:44:30.405646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '8849c688d775'
down_revision: Union[str, Sequence[str], None] = '56f35dac21a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returnsfeatures', sa.Column('signal_1', sa.Float(), nullable=True))
    op.add_column('returnsfeatures', sa.Column('signal_5', sa.Float(), nullable=True))
    op.add_column('returnsfeatures', sa.Column('signal_10', sa.Float(), nullable=True))
    op.add_column('returnsfeatures', sa.Column('signal_20', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returnsfeatures', 'signal_20')
    op.drop_column('returnsfeatures', 'signal_10')
    op.drop_column('returnsfeatures', 'signal_5')
    op.drop_column('returnsfeatures', 'signal_1')
    # ### end Alembic commands ###
