"""added label to newsapi table

Revision ID: 9825d1580556
Revises: 604d72b1b59d
Create Date: 2026-06-23 14:14:58.981791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '9825d1580556'
down_revision: Union[str, Sequence[str], None] = '604d72b1b59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsAPI', 'label')
    # ### end Alembic commands ###
