"""added sentiment mean, title count etc..

Revision ID: bc19b6c4b575
Revises: 8849c688d775
Create Date: 2026-07-17 21:18:29.481848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'bc19b6c4b575'
down_revision: Union[str, Sequence[str], None] = '8849c688d775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('sentiment_mean', sa.Float(), nullable=True))
    op.add_column('NewsAPI', sa.Column('confidence_mean', sa.Float(), nullable=True))
    op.add_column('NewsAPI', sa.Column('title_count', sa.Integer(), nullable=True))
    op.add_column('NewsAPI', sa.Column('positive_count', sa.Integer(), nullable=True))
    op.add_column('NewsAPI', sa.Column('negative_count', sa.Integer(), nullable=True))
    op.add_column('NewsAPI', sa.Column('neutral_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsAPI', 'neutral_count')
    op.drop_column('NewsAPI', 'negative_count')
    op.drop_column('NewsAPI', 'positive_count')
    op.drop_column('NewsAPI', 'title_count')
    op.drop_column('NewsAPI', 'confidence_mean')
    op.drop_column('NewsAPI', 'sentiment_mean')
    # ### end Alembic commands ###
