"""Created new features tables

Revision ID: bdd4544445bf
Revises: c85db664ee38
Create Date: 2026-06-22 13:08:10.364834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'bdd4544445bf'
down_revision: Union[str, Sequence[str], None] = 'c85db664ee38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meanreversionfeatures',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zscore_10', sa.Float(), nullable=True),
    sa.Column('zscore_20', sa.Float(), nullable=True),
    sa.Column('zscore_50', sa.Float(), nullable=True),
    sa.Column('dist_mean_10', sa.Float(), nullable=True),
    sa.Column('dist_mean_20', sa.Float(), nullable=True),
    sa.Column('dist_mean_50', sa.Float(), nullable=True),
    sa.Column('vwap_dist', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meanreversionfeatures_symbol'), 'meanreversionfeatures', ['symbol'], unique=False)
    op.create_index(op.f('ix_meanreversionfeatures_timestamp'), 'meanreversionfeatures', ['timestamp'], unique=False)
    op.create_table('momentumfeatures',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rsi_7', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('rsi_21', sa.Float(), nullable=True),
    sa.Column('ema_dist_20', sa.Float(), nullable=True),
    sa.Column('ema_dist_10_50', sa.Float(), nullable=True),
    sa.Column('rsi_slope', sa.Float(), nullable=True),
    sa.Column('roc_10', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_momentumfeatures_symbol'), 'momentumfeatures', ['symbol'], unique=False)
    op.create_index(op.f('ix_momentumfeatures_timestamp'), 'momentumfeatures', ['timestamp'], unique=False)
    op.create_table('returnsfeatures',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_ret_1', sa.Float(), nullable=True),
    sa.Column('log_ret_5', sa.Float(), nullable=True),
    sa.Column('log_ret_10', sa.Float(), nullable=True),
    sa.Column('log_ret_20', sa.Float(), nullable=True),
    sa.Column('pct_ret_1', sa.Float(), nullable=True),
    sa.Column('pct_ret_5', sa.Float(), nullable=True),
    sa.Column('pct_ret_10', sa.Float(), nullable=True),
    sa.Column('pct_ret_20', sa.Float(), nullable=True),
    sa.Column('roll_cum_ret_20', sa.Float(), nullable=True),
    sa.Column('roll_mean_ret_20', sa.Float(), nullable=True),
    sa.Column('roll_ret_z_20', sa.Float(), nullable=True),
    sa.Column('fwd_ret_1', sa.Float(), nullable=True),
    sa.Column('fwd_ret_5', sa.Float(), nullable=True),
    sa.Column('fwd_ret_10', sa.Float(), nullable=True),
    sa.Column('fwd_ret_20', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returnsfeatures_symbol'), 'returnsfeatures', ['symbol'], unique=False)
    op.create_index(op.f('ix_returnsfeatures_timestamp'), 'returnsfeatures', ['timestamp'], unique=False)
    op.create_table('volatilityfeatures',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vol_5', sa.Float(), nullable=True),
    sa.Column('vol_10', sa.Float(), nullable=True),
    sa.Column('vol_20', sa.Float(), nullable=True),
    sa.Column('vol_ratio_10_50', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('bb_width_20', sa.Float(), nullable=True),
    sa.Column('vol_of_vol', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volatilityfeatures_symbol'), 'volatilityfeatures', ['symbol'], unique=False)
    op.create_index(op.f('ix_volatilityfeatures_timestamp'), 'volatilityfeatures', ['timestamp'], unique=False)
    op.create_table('volumefeatures',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vol_change', sa.Float(), nullable=True),
    sa.Column('vol_z_20', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('price_vol_interaction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volumefeatures_symbol'), 'volumefeatures', ['symbol'], unique=False)
    op.create_index(op.f('ix_volumefeatures_timestamp'), 'volumefeatures', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volumefeatures_timestamp'), table_name='volumefeatures')
    op.drop_index(op.f('ix_volumefeatures_symbol'), table_name='volumefeatures')
    op.drop_table('volumefeatures')
    op.drop_index(op.f('ix_volatilityfeatures_timestamp'), table_name='volatilityfeatures')
    op.drop_index(op.f('ix_volatilityfeatures_symbol'), table_name='volatilityfeatures')
    op.drop_table('volatilityfeatures')
    op.drop_index(op.f('ix_returnsfeatures_timestamp'), table_name='returnsfeatures')
    op.drop_index(op.f('ix_returnsfeatures_symbol'), table_name='returnsfeatures')
    op.drop_table('returnsfeatures')
    op.drop_index(op.f('ix_momentumfeatures_timestamp'), table_name='momentumfeatures')
    op.drop_index(op.f('ix_momentumfeatures_symbol'), table_name='momentumfeatures')
    op.drop_table('momentumfeatures')
    op.drop_index(op.f('ix_meanreversionfeatures_timestamp'), table_name='meanreversionfeatures')
    op.drop_index(op.f('ix_meanreversionfeatures_symbol'), table_name='meanreversionfeatures')
    op.drop_table('meanreversionfeatures')
    # ### end Alembic commands ###
