"""changed timestamp to publishedAt


Revision ID: c85db664ee38
Revises: cc54f96c2aa6
Create Date: 2026-06-19 17:02:34.045722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c85db664ee38'
down_revision: Union[str, Sequence[str], None] = 'cc54f96c2aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('publishedAt', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_NewsAPI_timestamp'), table_name='NewsAPI')
    op.drop_column('NewsAPI', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_NewsAPI_timestamp'), 'NewsAPI', ['timestamp'], unique=False)
    op.drop_column('NewsAPI', 'publishedAt')
    # ### end Alembic commands ###
