"""added description/content to newsapi

Revision ID: cc54f96c2aa6
Revises: 6b0d51391066
Create Date: 2026-06-19 16:56:54.179242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'cc54f96c2aa6'
down_revision: Union[str, Sequence[str], None] = '6b0d51391066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewsAPI', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('NewsAPI', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NewsAPI', 'content')
    op.drop_column('NewsAPI', 'description')
    # ### end Alembic commands ###
