"""added regime table

Revision ID: f18b8e1afe57
Revises: 28d1bfe34a7d
Create Date: 2026-07-21 19:19:57.671837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'f18b8e1afe57'
down_revision: Union[str, Sequence[str], None] = '28d1bfe34a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regimefeatures',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regimefeatures_symbol'), 'regimefeatures', ['symbol'], unique=False)
    op.create_index(op.f('ix_regimefeatures_timestamp'), 'regimefeatures', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regimefeatures_timestamp'), table_name='regimefeatures')
    op.drop_index(op.f('ix_regimefeatures_symbol'), table_name='regimefeatures')
    op.drop_table('regimefeatures')
    # ### end Alembic commands ###
